### ISSUE TITLE
Incorrect values in arrows kata

### ISSUE THREAD

**Issue by walterlatimer** [tddbin/katas#20]
```javascript
  it('one parameter can be written without parens', () => {
    var func = p => param - 1;
    assert.equal(func(23), 24);
  });
```

Pretty sure `func(23)` should be `func(25)`.

**Comment by wolframkriesing** [comment]
Hi Walter,

actually the second line can be changed too, so there is no need to adjust the assert-line.
the function may also become `var func = param => param + 1;` is one way

**Comment by walterlatimer** [comment]
Hi Wolfram!

While true, that isn't the point of the kata, which is to understand how arrows work.

**Comment by wolframkriesing** [comment]
as you can see here https://github.com/walterlatimer/katas/commit/4adb956fefe838690dd9a78ddf9ed4e854d57179 I intentionally changed it, since I develop the katas so that they pass first, but will merge the attached PR now, since I agree on your point ... thx
