### ISSUE TITLE
ES6 Kata 69 "Reflect - defineProperty" kata needs updating

### ISSUE THREAD

**Issue by csakai** [tddbin/katas#25]
Related: [es6katas.org:#31](https://github.com/tddbin/es6katas.org/issues/31)

Practicing `Reflect.defineProperty` while focusing on one parameter at a time will not provide a good understanding of the function if the third parameter is omitted. `Reflect.defineProperty` will throw if it does not receive an object as its third parameter. 

The following test will always pass:

```
//@@line 17~21
  describe('the 1st parameter is the object on which to define a property', function() {
    it('fails if it is not an object', function() {
      let noObj = {};
      assert.throws(() => { Reflect.defineProperty(noObj); }, TypeError);
    });
```

The following tests will always fail:

```
//@@line 22~29
    it('accepts an object', function() {
      let obj = '';
      assert.doesNotThrow(() => { Reflect.defineProperty(obj); });
    });
    it('accepts an instance (of a class)', function() {
      let instance;
      assert.doesNotThrow(() => { Reflect.defineProperty(instance); });
    });
//@@line 91~95
      it('when no 3rd parameter, the descriptor is given', function() {
        let instance = new class {};
        const wasPropertyDefined = Reflect.defineProperty(instance, 'prop', {value: 1});
        assert.equal(wasPropertyDefined, false);
      });
```

since `Reflect.defineProperty` throws when the third param is not an `object` (in these cases, the third param would be `undefined` if the user tries to abide the assertion statements).

Not too sure what's going on here:

```
//@@line 85~90
    describe('returns false', function() {
      it('when no property name is given (since no property has been added)', function() {
        let instance = new class {};
        const wasPropertyDefined = Reflect.defineProperty;
        assert.equal(wasPropertyDefined, false);
      });
```

If you specify the second param as _no property name_ or `''`, this returns `true` because the property is assigned to `instance['']`, causing the test to fail.

```
let instance = new class{}
Reflect.defineProperty(instance, '', {value: 'foo'})
instance[''] //returns 'foo'
```

**Comment by wolframkriesing** [comment]
its the same thing as this, issue, right?
https://twitter.com/mkuehnel/status/769661864464748544
any suggestions to fix it?

**Comment by csakai** [comment]
These are not quite the same issue, as one requires an array-like (`Reflect.apply`), and the other requires an object (`Reflect.defineProperty`), but the issues are rooted in the same general place - The third param cannot be omitted when demonstrating how the functions work.

A potential solution is to amend your approach to teaching the user how these functions work. Instead of introducing each param separately, each param must be included in each function call.

For example, there can't be any tests where the third param is undefined (Unless you want to indicate that the function will throw if the third param is not an object).

The test 'returns false -> when no property name is given (since no property has been added)' is not valid since the function will throw if you don't give an object as the third param. However, if you do provide an object as the third param, but the second param is `"" (empty string)`, it will still not return false, because the property will be defined on the key `"" (empty string)` of the given object.

**Comment by KingWarin** [comment]
@wolframkriesing our twitter conversation is related to issue no. 31 (as stated on top of this site by @csakai )

Possible solution if you want to keep the one param per test approach could be a wrapper for the functions where the params are optional, but I'm not sure if that might cause more confusion instead of being a real help.
As Chris said, the problems root is the same, so this approach is applicable on both issues.

**Comment by wolframkriesing** [comment]
i believe I fixed it in https://github.com/tddbin/katas/pull/44 correct?
If not please reopen this issue. thx
