### ISSUE TITLE
Solution for Kata 40 freezes the browser tab

### ISSUE THREAD

**Issue by arabindadora** [tddbin/katas#28]
Hello there!

Solution for Kata 40 freezes the browser tab, not sure why: https://gist.github.com/nullv01d/f114cb4560750834d4c57f25d8da2551

It's replicable on Chrome, IE and Firefox.

**Comment by shinenelson** [comment]
Sorry for getting to this too late, but I think I figured your issue out. I'm not sure whether you'd still be interested in this issue or the solution, but I thought I'll give some kind of a solution / closure to this issue.

I was able to reproduce this issue on Firefox as well. ( Fortunately, the state of the browser has improved a lot from 4 years ago, so now, we have the option to debug or even stop the offending script to escape the tab freeze )

Now, coming to the actual issue. On [line 31](https://gist.github.com/nullv01d/f114cb4560750834d4c57f25d8da2551#file-es6kata-40-js-L31), you've changed the value for `done` from `consumableUsers.anyLeft` to just simply `!anyLeft`. With or without the not ( `!` ), `anyLeft` would be incorrect. Reverting that to `consumbaleUsers.anyLeft` with or without the not would avoid the freezing of the browser tab.
