### ISSUE TITLE
Question about what to fix in parseInt

### ISSUE THREAD

**Issue by flobjective** [tddbin/katas#89]
Hi there,

I don't really get whether I should just implement `parseInt` here or also fix the tests ? On `https://tddbin.com/#?kata=es1/language/global-api/parseInt` it is showing `var numericString = '';` compared to here:
https://github.com/tddbin/katas/blob/de69cd582256ba2fcf648b16ea4b8386d7699f3b/katas/es1/language/global-api/parseInt.js#L14

**Comment by wolframkriesing** [comment]
Hi there, do the instructions in line 2 and 3 not really help? These tests, katas are meant for learning certain features by using them. Using them in the way of fixing the tests and make them green. The test descriptions do hopefully tell what there is to learn and how to do it.
Does that make sense?

**Comment by flobjective** [comment]
Nevermind, I apparently wasn't it reading carefully enough to understand that fixing the tests is okay except for the lines with assertions in it.
And btw. great job!

**Comment by wolframkriesing** [comment]
actually this is good input, because it makes me think if it should not be done better introducing what jskatas.org is about, right?
